### ISSUE TITLE
Did I successfully suggest changes?

### ISSUE THREAD

**Issue by clibassi** [LOST-STATS/lost-stats.github.io#108]
I think maybe I am messing up how I am suggesting edits to pages but I'm not sure. I know I'm a contributor, so I don't think I'm supposed to be doing PRs, but I have been submitting my edits by just clicking the green "Propose changes" button at the bottom of each page. Should I be doing anything else? Over the last few days I made some modifications on the synthetic control page, the density plots page, and the support vector machines page.

**Comment by NickCH-K** [comment]
That should work fine! Are the changes showing up on the live site?

**Comment by clibassi** [comment]
Not that I can see - that's why I got a little worried.
________________________________

**Comment by NickCH-K** [comment]
Hmm, that's weird. Actually, now that I think of it, I thought you were talking about the "Edit this page on Github" link at the bottom of each page. I'm not familiar with the "Propose changes" button

**Comment by clibassi** [comment]
Well - when I hit the “Edit this page” button and then make the edits, then there is a green button at the bottom that I can press to propose the changes I’ve made to the page. Maybe it is happening on a fork or something?
________________________________

**Comment by NickCH-K** [comment]
Hmm, maybe! Check if there's a LOST fork on your account. I don't see it as a pull request.

I wonder if maybe you're pushing changes to the Master branch rather htan the Source branch by accident. If that's the case, your edits would be overridden every time it remakes the website, since it takes the Source files and builds the site in Master

**Comment by clibassi** [comment]
Hmm so I think I found this fork of mine - maybe my changes are there?: https://github.com/clibassi/lost-stats.github.io 

Also if it's at all helpful, here's what I see when I go to make edits: 
[
![recording](https://user-images.githubusercontent.com/10570262/116000653-24d1d500-a5bf-11eb-9088-d5b6045b40af.gif)
](url)

**Comment by NickCH-K** [comment]
Could be, but the last commit on that fork is from January of last year so it doesn't seem likely.

I'd have expected that a "Propose changes" button would make a pull request but I don't see any from you. I'm just not familiar with the Propose system. @khwilson do you have any idea how this works?

**Comment by clibassi** [comment]
Thanks to the github support community I think I figured out how to submit a PR. Once I get confirmation on your end, we can close this issue, I think.

**Comment by NickCH-K** [comment]
Looks like it's working now!

**Comment by khwilson** [comment]
Gah! Sorry I missed this. Seems like it got resolved?

**Comment by NickCH-K** [comment]
Yep, fine now
