### ISSUE TITLE
Causal Forest Walkthrough is wrong for the stata - R interface example

### ISSUE THREAD

**Issue by ignacio-rh** [LOST-STATS/lost-stats.github.io#149]
Hey, 

Really cool resource guys!
There is a mistake on this tutorial explaining how to train causal forests: 
https://lost-stats.github.io/Machine_Learning/causal_forest.html 

In the stata part, you split data into test and training using 
g split = runiform() > .5

and you send over the testing data with the preserve block and calling 
keep if split == 0

But at not point do you call 
keep if split == 1

to explicitly only keep the training data for the training!

I believe after the preserve block 

```
preserve
* Keep the predictors from the holding data, send it over, so later we can make an X matrix to predict with
keep if split == 0
keep year prbarr prbconv prbpris avgsen polpc density taxpc regionn smsan pctmin wcon
* R needs that data pre-processed! So using the same variables as in the main model, process the variables
fvrevar year prbarr prbconv prbpris avgsen polpc density taxpc i.regionn i.smsan pctmin wcon
keep `r(varlist)'
* Then send the data to R
rcall: df.hold <- st.data()
restore

```
You just need to add one line which is 
keep if split == 1

So that you train with the training data and not the whole dataset.

Thanks!

**Comment by NickCH-K** [comment]
Thank you for the heads up! Fixed with 4eb756b1132d91cdfdbf8b58c3e131d1f2e25b24
