### ISSUE TITLE
Pushed color palette image files to wrong folder

### ISSUE THREAD

**Issue by aidan-bergsman** [LOST-STATS/lost-stats.github.io#160]
Hi all, I recently uploaded a page on color palettes and pushed the image files to the figures subdirectory instead of the images subdirectory within the figures subdirectory. Any idea on how I can move them to the proper location so that the graphs can show up on the LOST page?

**Comment by aidan-bergsman** [comment]
update: I tried deleting the images and pushing them again, but they still end up in the "figures" subdirectory. Not sure how to move them to the images folder there.

**Comment by NickCH-K** [comment]
Ok, should be fixed now. Added code chunks to your page, moved the images, and directed the image URLs to the proper spot.  If you could go back and add alt text to your images (in the [] part of the ![]() code) that would be great.

**Comment by NickCH-K** [comment]
Thanks for contributing!

**Comment by aidan-bergsman** [comment]
I'll go ahead and add the alt text, thanks for your help!!
