### ISSUE TITLE
nokogiri dependency

### ISSUE THREAD

**Issue by NickCH-K** [LOST-STATS/lost-stats.github.io#18]
I keep getting warnings that there is a security hole in the nokogiri dependency. Is this something to be worried about (or fixed) @khwilson ?

**Comment by khwilson** [comment]
Hey Nick. Sorry about missing this. Crazy couple weeks. :-)

I wouldn't worry about it, but I'll bump!

**Comment by khwilson** [comment]
All bumped! Adding the conda page I promised now. :-)
