### ISSUE TITLE
DID event study based on extremely large data

### ISSUE THREAD

**Issue by bright1993ff66** [LOST-STATS/lost-stats.github.io#219]
Hi, thanks so much for creating a series of tutorials mentoring us how to improve our data analysis skills!

I am conducting one research using DID method to investigate a causal relationship between a series of events and people. I tried to run your R codes from [this tutorial here](https://lost-stats.github.io/Model_Estimation/Research_Design/event_study.html). But I got memory error since I have a huge data to test (about 83 million rows, 7 gigabytes) 😭 

Do you have any suggestions about conducting the DID analysis based on such size of data? [The R package biglm](https://cran.r-project.org/web/packages/biglm/index.html) might be an answer but I am not sure if it works...

Thank you for your time!

**Comment by grantmcdermott** [comment]
Take a look at the Python [duckreg](https://github.com/py-econometrics/duckreg/blob/master/notebooks/event_study.ipynb) package. I have an R implementation that's almost fully baked, but not quite ready yet...

**Comment by bright1993ff66** [comment]
Thanks so much! I use Python more frequently actually 😆 @grantmcdermott
