### ISSUE TITLE
access to the repo

### ISSUE THREAD

**Issue by pramod-dudhe** [LOST-STATS/lost-stats.github.io#22]
Hi,
I have created 'faceted graphs' R markdown document but I am not able to create pull request to submit it. Pls give me access to LOST-STATS repo so that I can push my work to the repo. My git handle is pramod-dudhe.

Thanks,
Pramod

**Comment by NickCH-K** [comment]
Awesome! Just added you as a collaborator. Make sure your doc aligns with our [New Page Template](https://github.com/LOST-STATS/lost-stats.github.io/edit/source/NewPageTemplate.md) before pushing. Keep in mind you'll be uploading a Markdown doc, not an RMarkdown doc.
