### ISSUE TITLE
Stylistic (documentation) changes

### ISSUE THREAD

**Issue by grantmcdermott** [LOST-STATS/lost-stats.github.io#4]
@NickCH-K and I have discussed some of these over Twitter, but I'm going to jot down a laundry list of stylistic elements that I feel could be improved/changed. These are pretty opinionated, so I'd welcome thoughts from others.

- **Package names:** Following JOSS, the R Journal and others, package names in the text should be in bold rather than code. If possible, the package homepage should also be hyperlinked when it is first mentioned. i.e. "...using the **lfe** package ([link](https://cran.r-project.org/web/packages/lfe/index.html)) we can...", rather than "...using the `lfe` package we can...". Code should be reserved for, well, code. Similarly, we can revert to code when referring to a specific function from that package. (E.g. "Use the `lfe::felm()` function..." is fine.)
- **Use of grandchild pages.** We have support for grandchild pages and I think we should use them, or else individual topics are going to be become pretty unwieldy. Conversely, the default alphabetical ordering means that closely related topics might not be indexed in an optimal way (e.g. logit and probit models). Another example might be non-standard errors: HC, HAC and clustered SEs probably all deserve their own page. A three-level page hierarchy of _Model estimation -> Non-standard errors -> HC_ (and _HAC_ and _Clustered SEs_) makes sense to me. 
- **Implementation position:** Should we move the "Implementation" sections higher up on the page? I feel like this is the main reason people are going to be using LOST and at present they first have to scroll down passed the "Keep in Mind" and "Also consider" sections before hitting pay dirt. Maybe these two sections could be moved below "Implementations" instead?
- **Section TOC:** Relatedly...This one is potentially more complicated, but should we have a section TOC at the top of every page? I think this could be automated with git-hooks and [doctoc](https://github.com/thlorenz/doctoc#usage-as-a-git-hook). But I'll let @khwilson weigh in here.

**Comment by NickCH-K** [comment]
I'll work on changing the way package names are referred to.

Thumbs-up from me on grandchild pages. I wasn't able to get it to work when I was porting everything over (thus dataset combination no longer being in a grandchild format) so I may need some guidance here (and on the Contributions page).

I'm not so sure about moving Implementations. The concern that I have is that Implementations has the potential to end up being very long if lots of languages are added, and most people probably won't scroll to the bottom for the rest. Keep in Mind and Also Consider should be pretty short, and they will include some "best-practices" information we probably want to be a little more difficult to skip.

**Comment by khwilson** [comment]
From an interface perspective for implementations, you can do a simple accordion to hide the language you don't want. In a future version, it might make sense to have a "preferred language" so that your preferred language is always open by default.

You could also do a tabbed interface.

Just spitballing :)

**Comment by grantmcdermott** [comment]
Nick, here's an example of grandchild page: https://lost-stats.github.io/Model_Estimation/Nonstandard_Errors/HC/hc_se.html

The YAML actually stays pretty much the same. Even the optional `grand_parent: GRAND_PARENT TITLE` field is just for full indexing on the LHS. Everything will still work without it as long as you've correctly specified a parent... 

Speaking of which, you might have run into problems previously because you forgot to change the `has_children` field of the parent's YAML to "true"? (See [here](https://raw.githubusercontent.com/LOST-STATS/lost-stats.github.io/master/Model_Estimation/Nonstandard_Errors/nonstandard_erors.md).)

**Comment by NickCH-K** [comment]
Strange, I think I was doing all of that, including `has_children`, but all the grandchildren pages were showing up as top-level along with Model Estimation, etc. Not sure what I was doing but it seems to be working now!

**Comment by grantmcdermott** [comment]
Okay, here's my proposed tree structure for the Model estimation section (incl. some example pages that have yet to be added):

- Linear models
  - Ordinary Least Squares (Linear Regression)
  - Fixed Effects
  - Random Effects
- Generalised models
  - Probit Model
  - Logit Model
  - McFadden's Choice Model (Alternative-Specific Conditional Logit)
  - Heckman Correction Model
- Nonstandard Errors
  - HC
  - HAC
  - Cluster-robust SEs

Thoughts?

**Comment by NickCH-K** [comment]
I'm not sure I like the "Generalized Models" title - seems vague. Perhaps Non-Linear Models (to pair with Linear Models)? Heckman would have to move. Perhaps "Multiple Equation Models" which would also end up getting IV, SEM, SUR, etc.
