### ISSUE TITLE
Multilevel Models

### ISSUE THREAD

**Issue by pmeiners** [LOST-STATS/lost-stats.github.io#5]
I couldn't find any mention of general multilevel models on the Desired Nonexistent Pages page.
Did I miss the right page, or is there a specific reasons against providing a basic explanation of multilevel models?

**Comment by NickCH-K** [comment]
There's one mention there I think, for hierarchical Bayes for multinomial logit, but in general I think just nobody thought to add it! Definitely feel free to make multilevel model pages, or add it to the Desired Nonexistent Pages page.

**Comment by grantmcdermott** [comment]
There's also [this page](https://lost-stats.github.io/Model_Estimation/random_mixed_effects_estimation.html).

TBH though, I've been wondering whether we should restructure the page/index nesting for this part of the site to make the sub categories clearer. (Like we did for [Nonstandard errors](https://lost-stats.github.io/Model_Estimation/Nonstandard_Errors/nonstandard_errors.html).) @NickCH-K what do you think about nesting like:

- Linear models
   - OLS
  - Fixed effects
  - etc
- Generalised models
   - logit
   - etc.
- Multilevel models
   - Random effects
   - Bayesian hierarchical models
   - etc

**Comment by NickCH-K** [comment]
Breaking it up makes sense to me! There was naturally going to have to be a point where we'd have to break it up as we got more pages. 

Figuring out hte categories is a bit tougher, as whatever we pick there's likely to be some overlap. For example, many multilevel models are linear, so I'm not sure "Linear" is the right word for OLS/FE. But maybe Ordinary Least Squares / Generalized Linear Models / Random-Coefficient Models / Multinomial Models /(Other?)?

**Comment by grantmcdermott** [comment]
Yeah, overlap cases are unfortunate, but I think the pros of nesting outweigh the negatives. Let me open up a new issue where we can brainstorm categories and then I'll try to implement soon.
