### ISSUE TITLE
Add a test script?

### ISSUE THREAD

**Issue by pdeffebach** [LOST-STATS/lost-stats.github.io#6]
Many of the examples in this are broken, for example in the balance test, the guide instructs us to do 

```
bal.text(treat ~ foreign, data = mtcars)
```

Despite the fact that neither `treat` nor `foreign` exist in the `mtcars` dataset. Looking through the code-base, there doesn't seem to be an automated testing for this repository. Is this something on the radar?

**Comment by NickCH-K** [comment]
Hmm, good catch. I've corrected that particular error, but automated testing would be very cool if possible. I'm not sure how feasible it is. Does anyone know?

**Comment by NickCH-K** [comment]
Which other pages are broken, by the way? I've tested quite a few recently and they've worked fine. At most they should require a package install.

**Comment by khwilson** [comment]
It's possible, but a bit more of a pain. There are methods like Python's
doctests (liberally employed by Sage) and examples like sklearn's
exceedingly wonderful documentation.

The big problem is the assumed imports and data loads. But definitely
totally possible to write for all open source languages. Stata, SAS, etc
will be basically impossible.

Kevin

**Comment by khwilson** [comment]
Done!
