### ISSUE TITLE
Convert Absolute Links to Relative Links

### ISSUE THREAD

**Issue by khwilson** [LOST-STATS/lost-stats.github.io#60]
Breaking out off-topic discussion from #55 into a new issue....

In order to support better proofing and modularity, we should change all the absolute links (e.g., `https://lost-stats.github.io/Time_Series/model.html`) to Liquid-friendly relative links, i.e.,

```
{{ "/Time_Series/model.html" | relative_url }}
```

This will allow #59 to more easily pick out dead links as well as making TOC migrations easier.

**Comment by khwilson** [comment]
cc @grantmcdermott

**Comment by khwilson** [comment]
See #63

**Comment by NickCH-K** [comment]
I will get into the habit of fixing links regularly. Where is the best spot to see the html-proofer output?

**Comment by khwilson** [comment]
Every time someone pushes to a PR or otherwise, Github will run html-proofer on its way to building the site.

**In a PR**

In a PR, you can click the `Checks` tab:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/1527442/97096815-66e58280-163f-11eb-8e47-c55da5e42a2b.png">

Then you choose a job on the left-hand side (they're identical jobs, but for lazy reasons there are two of them, so either is fine):
<img width="386" alt="image" src="https://user-images.githubusercontent.com/1527442/97096821-7bc21600-163f-11eb-85d8-f96e4178600e.png">

Then choose a specific run, in this case `build_job`:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/1527442/97096829-90061300-163f-11eb-9598-ca26c5c4e25c.png">

Then look for the `Check for broken links` step:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1527442/97096831-9bf1d500-163f-11eb-9329-010dcba123e5.png">

~~~~~~~~~~~~~

**For any other push**

You can click the `Actions` tab on the main page and then just choose a job. Follow the same steps as above to see the output of `html-proofer`.

~~~~~~~~~~~~~

**Locally**

You can also run locally, you can just run `bundle exec jekyll build` followed by `bundle exec htmlproofer --assume-extension --allow-hash-href ./_site`

**Comment by khwilson** [comment]
Notably, it also checks for things like missing img alt tags :-)

**Comment by NickCH-K** [comment]
Thanks!

**Comment by grantmcdermott** [comment]
Super work @khwilson. Any reason you still want to keep this open, or can we close?

**Comment by khwilson** [comment]
Can definitely close!
