### ISSUE TITLE
New security advisory

### ISSUE THREAD

**Issue by NickCH-K** [LOST-STATS/lost-stats.github.io#61]
There's a "high severity" security issue listed [here](https://github.com/LOST-STATS/lost-stats.github.io/network/alert/package-lock.json/bl/open). I think I see the fix but don't want to break whatever the GH-actions flow is. @khwilson how should this be fixed?

**Comment by khwilson** [comment]
Hey @NickCH-K sorry I missed this! Will take a look now. :-)

**Comment by khwilson** [comment]
Took care of this with #62 Feel free to review. :-)

**Comment by khwilson** [comment]
#62 is merged, so we can close this.
