### ISSUE TITLE
Markdown tables not compiling

### ISSUE THREAD

**Issue by NickCH-K** [LOST-STATS/lost-stats.github.io#66]
I was just taking a look at the page for [Combining Datasets Overview](https://lost-stats.github.io/Data_Manipulation/Combining_Datasets/combining_datasets_overview.html) and the Markdown tables used at the top are not being shown as tables. They show up properly in the [code/Markdown preview](https://github.com/LOST-STATS/lost-stats.github.io/blob/source/Data_Manipulation/Combining_Datasets/combining_datasets_overview.md) for that page, but not the final version. How can we fix this?

**Comment by khwilson** [comment]
See #68
