### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by NickCH-K** [LOST-STATS/lost-stats.github.io#71]
I made a few commits and kept getting the following error when it tries to push to Pages:

```
Error: Unable to process command '::set-env name=DEPLOYMENT_STATUS::success' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Any idea how to fix this?

**Comment by khwilson** [comment]
Oh, yes, this occurred in a few other commands. Should be fixed now. :-)

Kevin

**Comment by khwilson** [comment]
See https://github.com/LOST-STATS/lost-stats.github.io/commit/5bf6a2416a843b1cf9515a11e045885d48338f4a

**Comment by khwilson** [comment]
Seems to have worked! https://github.com/LOST-STATS/lost-stats.github.io/runs/1442673315?check_suite_focus=true Closing.
