### ISSUE TITLE
Adding python code for fixed effect and data.table for reshaping in R

### ISSUE THREAD

**Issue by wensongz-uo** [LOST-STATS/lost-stats.github.io#79]
Hi, 

I made a few edits in the Data Manipulations by add data.table code for reshaping (both long-to-wide and wide-to-long), and also in OLS by adding Python code for fixed effects regression.

Would you please add me as the contributor so that I can push my changes to the repo and make a pull request? Currently, when I push, it consistently says "The requested URL returned error: 403".

Best,
Wensong

**Comment by NickCH-K** [comment]
Added!
