### ISSUE TITLE
Standard Environments

### ISSUE THREAD

**Issue by khwilson** [LOST-STATS/lost-stats.github.io#8]
I think it would be great if all the examples here assumed standard environments and we added a page about it. It would also allow #6 to actually happen.

E.g., for R, you should `install.packages(c('tidyverse', 'mass'))` or whatnot.

Thoughts?

**Comment by NickCH-K** [comment]
I'm not sure if this would work for languages, like R, that might well need a new package install on almost every page. But if there were a page for maintainers to add all installed packages used in their pages, that would address this, yes?

**Comment by khwilson** [comment]
That's what I was thinking. Something like, "assume in every R example we have `library(tidyverse)` at the top, but specify more specific libraries in each example.

**Comment by NickCH-K** [comment]
Hmm, that would mean that users couldn't copy the code chunks and have them just work though.

Would it achieve a similar goal to have the package installation lines in the code itself (or have them all assembled on another page for all used packages?)

**Comment by khwilson** [comment]
Fair point! I'm also thinking of it though as a teaching tool for setting up your environment. At least in the python world, everyone has their standard preamble they copy and paste between notebooks. And in the R world, where namespace clobbering can occur, I assume people have very standardized import orders?

Happy to set this aside. :-)

**Comment by NickCH-K** [comment]
I think it varies a lot between languages. Something like Stata has no environment setup, generally, and for R the setup varies a lot between users and tasks - lots of people don't use tidyverse at all, for example.

**Comment by khwilson** [comment]
Stata does have some environment setup for things like custom commands, but
I know they’re relatively rare. Python and R both have major setup burdens.

I guess since the resource starts with “how do I join data sets?” I’m
wondering what you’re assuming of readers. Similarly, should every R
example have the three ways people tend to write R or should it be a bit
more opinionated?

Kevin

**Comment by NickCH-K** [comment]
What we're assuming of readers is a tricky question since different pages naturally will have audiences with different levels of sophistication, and there are always multiple ways to do things.

The way I tried to aim it on the Contributing page is that a given page should aim for the level of sophistication you'd expect of someone needing to read that page. And as for multiple ways to do things, it should be a little opinionated in presenting a good way and sticking to it, but if the multiple ways are meaningfully different, being willing to show multiple ways.

**Comment by khwilson** [comment]
While we don't have standard environments per se, #64 required creating more or less standard environments. See there for details.
